Repository knative-sandbox/actions-downstream-test, pull requests merged in 2022-04, with the labels that each got.

#22 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#23 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#25 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#26 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#27 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#20 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: size/XS, approved, lgtm

#28 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
